import{S as c,a as u,i}from"./assets/vendor-Bm2N4jGG.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const a={gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader")},f=new c(".gallery a",{captionsData:"alt"});function d(s){const o=s.map(r=>`<li class="gallery-item">
            <a href="${r.largeImageURL}">
              <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy"/>
            </a>
            <p><b>likes</b>: ${r.likes}</p>
            <p><b>views</b>: ${r.views}</p>
            <p><b>comments</b>: ${r.comments}</p>
            <p><b>downloads</b>: ${r.downloads}</p>
          </li>`).join("");a.gallery.innerHTML=o,f.refresh()}function m(){a.gallery.innerHTML=""}function p(){a.loader.classList.add("visible")}function y(){a.loader.classList.remove("visible")}const g="https://pixabay.com/api/";function h(s){return u.get(g,{params:{key:"55068901-115bb3486aee025ccc29fb7ad",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(o=>o.data)}const b={form:document.querySelector(".form")};b.form.addEventListener("submit",s=>{s.preventDefault();const o=s.target.elements["search-text"].value.trim();if(o===""){i.error({message:"Please enter a search query"});return}m(),p(),h(o).then(r=>{if(r.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}d(r.hits)}).catch(r=>{i.error({message:"Something went wrong. Please try again later."})}).finally(()=>{y()}),s.target.reset()});
//# sourceMappingURL=index.js.map
